// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using microservices_rabbit.model.Context;

#nullable disable

namespace microservices_rabbit.Migrations
{
    [DbContext(typeof(ShoppingCartContext))]
    [Migration("20221012162607_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("microservices_rabbit.model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Key");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 3L,
                            CategoryName = "Tecnologia",
                            Description = "Laptop da Apple",
                            ImageUrl = "abc123",
                            Name = "Macbook",
                            Price = 9999m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Saúde",
                            Description = "Bicicleta para pedalar",
                            ImageUrl = "abc123",
                            Name = "Bicicleta",
                            Price = 10000m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Limpeza",
                            Description = "Para tirar a gordura da cozinha",
                            ImageUrl = "abc123",
                            Name = "Desengordurante",
                            Price = 8.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
